### ISSUE TITLE
Script is unable to determin freguencies?

### ISSUE THREAD

**Issue by Overcon** [Sepero/temp-throttle#32]
Ran the script and tried to set the throttling and got this:

sudoroot@xpsl501x:~/stable/temp-throttle-stable$ ./temp_throttle.sh 98
Author: Sepero 2016 (sepero 111 @ gmx . com)
URL: http://github.com/Sepero/temp-throttle/

Number of CPU cores detected: 8

Error: Could not determine available cpu frequencies

**Comment by ghost** [comment]
Maybe it's too late as the maintainer of this project didn't respond either, but:

This script assumes to get a list of available CPU frequencies from **/sys/devices/system/cpu/cpu0/cpufreq/scaling_available_frequencies** in order to scale up and down. If it doesn't exist and there's no **cpuinfo_min_freq** and **cpuinfo_max_freq** either, you probably don't have a CPU frequency scaling module loaded.

If you're still on it, you might post the output of
`uname -a`
and
`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor`

This will tell what system and which CPU scaling governor you use (if a scaling module is loaded).

**Comment by Sepero** [comment]
I apologize for the late reply. I've made recent updates to the testing branch. Please check it out, and report back if you still have a problem.

**Comment by Sepero** [comment]
Modifications made to attempt compensating for missing scaling frequencies file. Please see testing branch.
