### ISSUE TITLE
crashes

### ISSUE THREAD

**Issue by ryzhikgagarin** [Sepero/temp-throttle#35]
Release 18.04.2 LTS (Bionic Beaver) 64-bit
Intel® Core™ i7-7500U CPU @ 2.70GHz × 4 
Kernel Linux 4.18.0-24-lowlatency x86_64
"cpufrequtils" installed. 

Run as: 
sudo temp_throttle.sh 80

Crashes after a while with a message:  
"Error: Failed to set frequency CPU core0. Run script as Root user. Some systems may require to install the package cpufrequtils."

**Comment by Sepero** [comment]
Apologies for my late reply. This is this line of code that appears to be failing

    echo $FREQ_TO_SET 2> /dev/null > /sys/devices/system/cpu/cpu$i/cpufreq/scaling_max_freq

Please reply with the output of these commands:

    sudo ls /sys/devices/system/cpu/
    sudo ls /sys/devices/system/cpu/cpu0/
    sudo ls /sys/devices/system/cpu/cpu0/cpufreq/
    sudo cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_frequencies
    sudo cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq

**Comment by ryzhikgagarin** [comment]
Thanx for reply. Here it is:

```
sudo ls /sys/devices/system/cpu/
cpu0  cpu1  cpu2  cpu3	cpufreq  cpuidle  hotplug  intel_pstate  isolated  kernel_max  microcode  modalias  offline  online  possible  power  present  smt  uevent  vulnerabilities
```
```
sudo ls /sys/devices/system/cpu/cpu0/
acpi_cppc  cache  cpufreq  cpuidle  crash_notes  crash_notes_size  driver  firmware_node  hotplug  microcode  node0  power  subsystem  thermal_throttle  topology  uevent
```
```
sudo ls /sys/devices/system/cpu/cpu0/cpufreq/
affected_cpus	  cpuinfo_min_freq	      energy_performance_available_preferences	related_cpus		     scaling_cur_freq  scaling_governor  scaling_min_freq
cpuinfo_max_freq  cpuinfo_transition_latency  energy_performance_preference		scaling_available_governors  scaling_driver    scaling_max_freq  scaling_setspeed
```
```
sudo cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_frequencies
cat: /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_frequencies: No such file or directory
```
```
sudo cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
3500000
```

**Comment by Sepero** [comment]
scaling_available_frequencies: No such file or directory

This seems to explain the problem here. Unfortunately, I can't be certain that we'll be able to fix it. To throttle the CPU, the program lowers the CPU frequencies as needed. For some reason the available frequencies file isn't showing up on your system. This same issue happens on some ARM architectures also. So to compensate, the program will read the max and min frequencies, and try to calculate some frequencies in between.

Since the available frequencies are unknown for your system, the program is trying to use calculated frequencies that are between the min and max. Your system is not accepting the calculated frequencies. This is giving us the error.

    Error: Failed to set frequency CPU core0

Is it possible that you are using a custom Linux kernel?

Perhaps a file with available frequencies does exist, but we don't know where. You could try a search, and if found, I could incorporate the new information. Please reply with output of this command.

    sudo find /sys -iname "*available*freq*"

As an option of last resort- we could make the program ignore the errors, and force it continue running. It's possible that some calculated frequencies are accepted, and some not accepted. If some calculated frequencies are accepted, then the program could still work, albeit slightly less efficiently.

**Comment by ryzhikgagarin** [comment]
No, I'm using the mainline kernel 4.18.0-25-lowlatency x86_64. 

`sudo find /sys -iname "*available*freq*"`
Shows nothing.

**Comment by ryzhikgagarin** [comment]
I have noticed strange thing that with or without your app the current frequency in idle is maximal or close to maximal, but sometimes it lowers down under load.

**Comment by Sepero** [comment]
I appreciate all the correspondence on your behalf. Your system may be slowing down under load if it already has a program like temp-throttle running in the BIOS. Which would make it slow down due to temperature heat. I'm not familiar with systems having such capability, but it is a possibility.

Sadly, without knowledge of the available frequencies, there doesn't appear to be anyway to directly solve the issue within temp-throttle.

If you would like to test running the program in spite of the errors. Depending on what branch you're using, you could edit the following line to see the output.
master branch #112
testing branch #147

Modify the code from "err_exit" to "echo". This modification is perfectly safe to make. (For future reference: the line begins as `err_exit "Failed to set frequ`)

From here I can only suggest to stay subscribed for updates. Perhaps someone else will have this problem also, and hopefully we can work out a solution.

**Comment by Sepero** [comment]
Frequencies between Max and Min are auto generated (guessed) if a frequency file is not found.
