### ISSUE TITLE
Was using RAM temp sensor 

### ISSUE THREAD

**Issue by demangler** [Sepero/temp-throttle#45]
I found it wasn't working as expected, some looking at actual temps revealed the RAM sensor was being used,
I just went through until I found one that correlated, and added

/sys/class/thermal/thermal_zone7/temp

to the top of the TEMPERATURE_FILES list in the script and after that it worked great.

I wonder if there is a better maybe more interactive way to make this more obvious to users, looking at type and allowing a choice, maybe.

Anyway - great script! :)
Thanks.

btw,
Dell 7577 laptop with Linux mint 20.

**Comment by Jeremy7701** [comment]
It is so variable, across machines
e.g. Mobo: ASUSTeK model: PRIME B550-PLUS
CPU:       Info: 8-Core model: AMD Ryzen 7 5800X

`inxi -s` produces
**Sensors:   System Temperatures: cpu: 27.1 C mobo: N/A gpu: nouveau temp: 36.0 C 
           Fan Speeds (RPM): N/A**

Alternatively, for a fuller picture, try
`neofetch --cpu_temp`
```
`.-::---..                     jeremy@hal 
      .:++++ooooosssoo:.       ---------- 
    .+o++::.      `.:oos+.     OS: LMDE 5 (elsie) x86_64 
   :oo:.`             -+oo:    Kernel: 5.10.0-15-amd64 
 `+o/`    .::::::-.    .++-`   Uptime: 36 mins 
`/s/    .yyyyyyyyyyo:   +o-`   Packages: 2864 (dpkg) 
`so     .ss       ohyo` :s-:   Shell: bash 5.1.4 
`s/     .ss  h  m  myy/ /s``   Resolution: 1920x1080 @ 60.00Hz 
`s:     `oo  s  m  Myy+-o:`    DE: Cinnamon 5.2.7 
`oo      :+sdoohyoydyso/.      WM: Mutter (Muffin) 
 :o.      .:////////++:        WM Theme: Mint-Y-Dark (Mint-Y) 
 `/++        -:::::-           Theme: Mint-X [GTK2/3] 
  `++-                         Icons: Mint-X-Dark [GTK2/3] 
   `/+-                        Terminal: gnome-terminal 
     .+/.                      CPU: AMD Ryzen 7 5800X (16) @ 3.800GHz [27.5°C] 
       .:+-.                   GPU: NVIDIA GeForce GT 1030 
          `--.``               Memory: 1596MiB / 32085MiB 
```

**Comment by Sepero** [comment]
Thanks for the feedback. It seems odd to me to have a temp sensor on the RAM, but I'm very pleased you were able to get it working. I could make a custom flag for which temperature sensor to use. I'll look into it.

**Comment by demangler** [comment]
Thanks - I don't know for sure if it is a RAM sensor, just that is what was in thermal_zoneN/type, but I have all sorts of weird extra hardware bolted on to this laptop so who knows.
The best use case for this script for me is when using an external GPU, this laptop has huge cooling and it just causes the cpu to run a lot faster (because it is on the same heat pipe as a now idle GPU) and the fans are working to provide unnecessary extra CPU. 
You might see a pull request,
Thanks again. :)

**Comment by Sepero** [comment]
Reworked code and should be fixed in the testing release branch.

**Comment by flying-x** [comment]
I am on arch linux with 6.6.26 kernel. It seems that it couldn't find the temp sensor file. psensor could get the correct Tctl and Tccd1 temp from the Ryzen CPU. Maybe the script need some update?

**Comment by flying-x** [comment]
I am guess that k10_temp module isn't working well. So I end up doing this:

```
# Get the temperature from selected sources, and find the highest temp.
get_temp () {   
        TEMP="$(cat $TEMPERATURE_FILES 2>/dev/null | xargs -n1 | sort -gr | head -1)"
        TEMP="$(sensors|grep Tctl|tr + ' '| tr ° ' ' | tr C ' '|xargs -n1 |sort -gr|head -1)"
        # float -> int
        TEMP=${TEMP%.*}
```

**Comment by Sepero** [comment]
Thanks for reporting! I've recently released a major upgrade to the script. Please tell me

What version are you using?

Where did you acquire it? (Github? AUR?)

Do you know the correct location to read temperature? Which file uri?

**Comment by flying-x** [comment]
I was using GitHub version. I end up using the sensors cmd to get the temp
and times 1000 and it works great now

**Comment by Sepero** [comment]
You got it working with a minor edit, that's great news. Do you happen to know the correct file location to read your CPU temperature?

I may be able to improve temp-throttle so that it doesn't require the sensors cmd.

**Comment by Sepero** [comment]
Also could you please send me the raw output of running sensors.

**Comment by flying-x** [comment]
The raw output:

```
nvme-pci-0200
Adapter: PCI adapter
Composite:    +23.9°C  (low  = -273.1°C, high = +81.8°C)
                       (crit = +84.8°C)
Sensor 1:     +23.9°C  (low  = -273.1°C, high = +65261.8°C)
Sensor 2:     +24.9°C  (low  = -273.1°C, high = +65261.8°C)

k10temp-pci-00c3
Adapter: PCI adapter
Tctl:         +30.5°C
Tccd1:        +24.0°C
```

**Comment by flying-x** [comment]
I think sensors cmd read it from these place:

```
cat /sys/class/hwmon/hwmon*/temp*_label
                                        ✔
Composite
Sensor 1
Sensor 2
Tctl
Tccd1
```

On my system, I think hwmon0 has three sensors from the NVME drive. hwmon1
has 2 sensors from the cpu. maybe that's why the script was initially
confused?

**Comment by flying-x** [comment]
To be exact, this is the file to read the cpu "Tctl" temp:
/sys/class/hwmon/hwmon1/temp1_input

**Comment by Sepero** [comment]
If the location is correct, then you can pass
/sys/class/hwmon/hwmon1/temp1_input

As an argument, and not need lm_sensors. You can set it either using /etc/temp-throttle.conf, or pass as a command line argument:


sudo temp-throttle -f /sys/class/hwmon/hwmon1/temp1_input -t 60

-t 60 for 60 degrees

Please let me know if you try it :)

-Sepero

**Comment by flying-x** [comment]
Sounds good. If the script can detect the file automatically it would be
great too.

**Comment by Sepero** [comment]
The script can detect your temperature file automatically, but is confused.

You can see that it tries to find the location here:
https://github.com/Sepero/temp-throttle/blob/fd4a429a3cba0eb980f91c81e9ef5bd70f4d94c2/usr/sbin/temp-throttle#L160

But that is not where the CPU temperature is "supposed" to be located. The CPU temperature is "supposed" to be located here:
/sys/class/thermal/thermal_zone*/temp

So if you have a file there (in thermal), the script will discard other locations.

I could make the script guess location better, but how can I know that Tctl is the CPU? How do I know it isn't Tccd1, or any other random temperature location? These are legitimate questions. If I could answer them, then I could improve things.

The output of sensors for me reads as follows:

nouveau-pci-0100
Adapter: PCI adapter
GPU core:    850.00 mV (min =  +0.85 V, max =  +0.95 V)
temp1:        +60.0°C  (high = +95.0°C, hyst =  +3.0°C)
                       (crit = +108.0°C, hyst =  +2.0°C)
                       (emerg = +110.0°C, hyst =  +5.0°C)

BAT0-acpi-0
Adapter: ACPI interface
in0:           3.86 V  
curr1:         0.00 A  

acpitz-acpi-0
Adapter: ACPI interface
temp1:        +51.0°C  

coretemp-isa-0000
Adapter: ISA adapter
Core 0:       +47.0°C  (crit = +105.0°C)
Core 1:       +48.0°C  (crit = +105.0°C)


At the bottom we can see on my dual core system, Core 0 and Core 1. That is the way I believe most systems output.

On one hand, If there is a way I can improve the script so that it encompasses a lot more CPUs, then I'll gladly make that change.

On the other hand, I'm unable to make special exceptions to try and chase every oddball temperature reporting that exists. Hopefully that makes sense.

I'm open to any ideas and feedback you have.

**Comment by flying-x** [comment]
yeah, totally makes sense.

The Tctl and Tccd1/2/3 etc are very standard for ryzen or epyc CPUs from
amd. They are becoming more and more popular. Those strings are coded in
the k10temp kernel module. They won't change easily. It might be good to
check cpu types from /proc/cpuinfo and then decide which temp file to use?
There is a label file contains the name which you can use to match the
string and then read the temp.

You can probably get a cloud instance of AMD cpus and test it out that way.
Should be very cheap.

Also, I use nvidia-smi etc to throttle GPU but not by temp dynamic. It
would cool to control GPUs this way with your script too. Understand if it
is too much work. Just mentioning in case it is your hobby to do it anyway.

**Comment by Sepero** [comment]
Please tell me more about this "label file". I'm not aware of such a thing.

**Comment by flying-x** [comment]
Sorry I wasn't clear. Here are the files on my system:

![image](https://github.com/Sepero/temp-throttle/assets/22962929/ef05de8b-ace1-4a83-9f48-d4ab0316ea18)

**Comment by flying-x** [comment]
They have corresponding temp*_input file too.

On my system, the first 3 are from NVME drive. The last 2 are from Ryzen CPU.

**Comment by flying-x** [comment]
If you check k10_temp kernel module's source, you will see those ryzen strings hard-coded there.

**Comment by Sepero** [comment]
I'm not any kind of expert in hardware, nor do I have many machines to test on.

This info exchange with you has made me realize that the old version of my script worked (sort of) successfully based on a huge flaw. That flaw was the script would throttle the CPU based on reading of Every temperature sensor on the machine. It would throttle the CPU if Any temperature exceeded max desired. If I had left it that way, then you may have never contacted me.

But I changed that behavior in the new version, because I learned that someone was having their CPU throttled based on high GPU temperature.

I tried to eliminate that flaw in the new version, but it looks like I have potentially invited a much greater problem. It's possible that many architectures (not just AMD) are reporting CPU temperature to places I couldn't anticipate. Now the New script may be broken for many people who the Old script was working.

I think I may need to modify the script operate based on the flawed model again, until I perhaps I can devise a better solution. I'll need to ponder on this for a bit.

Thank you

**Comment by Sepero** [comment]
As for script to throttle GPU, it's possible you could do it yourself. :)

1. Make a copy of the script to `gpu-throttle`
2. Mod the location to gather GPU frequency information. Lines 123, 124, 125
3. Mod the location to set frequency for GPU. Line 182

Run it with the -f argument to set the location to read GPU temperature.

sudo ./gpu-throttle -t 80 -f /sys/path/to/gpu/temp

**Comment by flying-x** [comment]
Thanks for the long explanation! I am glad that we both gained a better
understanding of things. :-)

I am actually totally fine with your script right now and happily using it.
Thank you for the great work!
